name: Run Gemini CLI (manual)
on:
  workflow_dispatch:

jobs:
  gemini:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Gemini CLI
        uses: google-github-actions/run-gemini-cli@v0.1.6
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: >
            Act as a research assistant for the repository “Researching the Origins of the Letter A.”
            1) Summarize the repo’s current state.
            2) Propose 3–5 concrete next tasks (PR-sized), each with a short rationale and expected files to add/change.
            3) Suggest one starter PR (branch name and files to create).
            Read and follow GEMINI.md if present.
