name: Gemini PR Review
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  review:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Run Gemini CLI
        uses: google-github-actions/run-gemini-cli@v0.1.6
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: >
            Review this pull request. One comment only, structured as:
            1) High-priority issues with rationale
            2) Concrete suggestions
            3) Nits/formatting
            4) Tests or checks to add
            Cite files/lines precisely. Respect any guidance in GEMINI.md.
